# Generated by Django 6.0.6 on 2026-06-24 04:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, unique=True, verbose_name='Country Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='Role Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Employee Role',
                'verbose_name_plural': 'Employee Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True, verbose_name='Status Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Employee Status',
                'verbose_name_plural': 'Employee Statuses',
                'db_table': 'EmployeeStatuses',
            },
        ),
        migrations.CreateModel(
            name='LeadActivityType',
            fields=[
                ('lead_activity_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_activity_type_name', models.CharField(max_length=50, unique=True, verbose_name='Lead Activity Type Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Lead Activity Type',
                'verbose_name_plural': 'Lead Activity Types',
                'db_table': 'LeadActivityTypes',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=50, unique=True, verbose_name='Source Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
                'db_table': 'LeadSources',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(max_length=50, unique=True, verbose_name='Manufacturer Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'db_table': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=50, unique=True, verbose_name='Payment Method Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'PaymentMethods',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid VIN format', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='VIN')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Year')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
                ('mileage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mileage')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Acquisition Cost')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Selling Price')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('CPO', 'Certified Pre-Owned')], max_length=20, verbose_name='Condition')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('IN_SERVICE', 'In Service')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('date_acquired', models.DateField(verbose_name='Date Acquired')),
                ('date_listed', models.DateField(blank=True, null=True, verbose_name='Date Listed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100, verbose_name='City Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='car_sales.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'Cities',
                'unique_together': {('city_name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+8801XXXXXXXXX' (14 characters).", regex='^\\+8801[3-9]\\d{8}$')], verbose_name='Phone Number')),
                ('customer_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Customer Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer_city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='car_sales.city', verbose_name='Customer City')),
                ('customer_country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='car_sales.country', verbose_name='Customer Country')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Employee Email')),
                ('emp_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+8801XXXXXXXXX' (14 characters).", regex='^\\+8801[3-9]\\d{8}$')], verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Employee DOB')),
                ('emp_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Employee Address')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Hire Date')),
                ('leave_start_date', models.DateField(blank=True, null=True, verbose_name='Leave Start Date')),
                ('leave_end_date', models.DateField(blank=True, null=True, verbose_name='Leave End Date')),
                ('assigned_task', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assigned Task')),
                ('terminated_date', models.DateField(blank=True, null=True, verbose_name='Terminated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('emp_city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='car_sales.city', verbose_name='Employee City')),
                ('emp_country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='car_sales.country', verbose_name='Employee Country')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='car_sales.employeerole', verbose_name='Role')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='car_sales.employeestatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTarget',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_goal', models.PositiveIntegerField(verbose_name='Target Goal (Products to Sell)')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Commission Percentage')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='car_sales.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Target',
                'verbose_name_plural': 'Employee Targets',
                'db_table': 'EmployeeTargets',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('NEGOTIATING', 'Negotiating'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='car_sales.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='car_sales.employee', verbose_name='Assigned Employee')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='car_sales.leadsource', verbose_name='Source')),
                ('vehicle', models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='car_sales.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Activity Date')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='car_sales.employee', verbose_name='Employee')),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='car_sales.lead', verbose_name='Lead')),
                ('activity_type', models.ForeignKey(db_column='lead_activity_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='lead_activities', to='car_sales.leadactivitytype', verbose_name='Lead Activity Type')),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'db_table': 'LeadActivities',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sale Date')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Base Price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax Amount')),
                ('commission_rate_applied', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Commission Rate Applied')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Commission Amount')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('FINANCING', 'Financing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='car_sales.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='car_sales.employee', verbose_name='Employee')),
                ('lead', models.OneToOneField(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='car_sales.lead', verbose_name='Lead')),
                ('vehicle', models.OneToOneField(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='car_sales.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('payment_method', models.ForeignKey(blank=True, db_column='method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='car_sales.paymentmethod', verbose_name='Payment Method')),
                ('sale', models.ForeignKey(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='car_sales.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='FinanceApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Loan Amount')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='finance_applications', to='car_sales.customer', verbose_name='Customer')),
                ('sale', models.OneToOneField(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, related_name='finance_application', to='car_sales.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Finance Application',
                'verbose_name_plural': 'Finance Applications',
                'db_table': 'FinanceApplications',
            },
        ),
        migrations.CreateModel(
            name='TradeIn',
            fields=[
                ('trade_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('appraised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Appraised Value')),
                ('allowance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Allowance Amount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sale', models.OneToOneField(blank=True, db_column='sale_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in', to='car_sales.sale', verbose_name='Sale')),
                ('vehicle', models.OneToOneField(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='trade_in', to='car_sales.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Trade-In',
                'verbose_name_plural': 'Trade-Ins',
                'db_table': 'TradeIns',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=50, verbose_name='Vehicle Model')),
                ('trim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trim')),
                ('body_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Body Type')),
                ('fuel_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fuel Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('manufacturer', models.ForeignKey(db_column='manufacturer_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='car_sales.manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Models',
                'db_table': 'VehicleModels',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='car_sales.vehiclemodel', verbose_name='Vehicle Model'),
        ),
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='car_sales.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Service',
                'verbose_name_plural': 'Vehicle Services',
                'db_table': 'VehicleServices',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name'], name='Customers_lastname_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='Employees_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='Sales_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='Leads_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='Leads_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='Vehicles_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['year'], name='Vehicles_year_idx'),
        ),
    ]
