# Generated by Django 6.0.6 on 2026-06-24 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Country ID')),
                ('country_name', models.CharField(max_length=100, unique=True, verbose_name='Country Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Role ID')),
                ('role_name', models.CharField(max_length=100, unique=True, verbose_name='Role Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'employee_role',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Status ID')),
                ('status', models.CharField(max_length=50, unique=True, verbose_name='Status Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'employee statuses',
                'db_table': 'employee_status',
            },
        ),
        migrations.CreateModel(
            name='IndustryInfo',
            fields=[
                ('make_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Make ID')),
                ('make_name', models.CharField(max_length=100, unique=True, verbose_name='Make Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'industry info',
                'db_table': 'industry_info',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='City ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='City Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='car_sales.country', verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Customer ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('customer_status', models.CharField(max_length=50, verbose_name='Customer Status')),
                ('customer_address', models.CharField(max_length=255, verbose_name='Customer Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='car_sales.city', verbose_name='City')),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='car_sales.country', verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'customer info',
                'db_table': 'customer_info',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Store ID')),
                ('store_name', models.CharField(max_length=150, verbose_name='Store Name')),
                ('store_code', models.CharField(max_length=20, unique=True, verbose_name='Store Code')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='car_sales.city', verbose_name='City')),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='car_sales.country', verbose_name='Country')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_joining', models.DateField(verbose_name='Date of Joining')),
                ('employee_addr', models.CharField(max_length=255, verbose_name='Employee Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='car_sales.city', verbose_name='City')),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='car_sales.country', verbose_name='Country')),
                ('employee_role', models.ForeignKey(db_column='employee_role', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='car_sales.employeerole', verbose_name='Employee Role')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='car_sales.employeestatus', verbose_name='Employee Status')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='car_sales.store', verbose_name='Store')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Vehicle ID')),
                ('vehicle_model', models.CharField(max_length=150, verbose_name='Vehicle Model')),
                ('mmr', models.IntegerField(verbose_name='MMR (Manheim Market Report)')),
                ('trim', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trim')),
                ('body', models.CharField(blank=True, max_length=100, null=True, verbose_name='Body')),
                ('transmission', models.CharField(blank=True, max_length=50, null=True, verbose_name='Transmission')),
                ('vin', models.CharField(max_length=20, unique=True, verbose_name='VIN')),
                ('state', models.CharField(blank=True, max_length=10, null=True, verbose_name='State')),
                ('condition', models.IntegerField(blank=True, null=True, verbose_name='Condition')),
                ('odometer', models.IntegerField(blank=True, null=True, verbose_name='Odometer')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('interior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Interior')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('make', models.ForeignKey(db_column='make_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='car_sales.industryinfo', verbose_name='Make')),
            ],
            options={
                'verbose_name_plural': 'vehicle info',
                'db_table': 'vehicle_info',
            },
        ),
        migrations.CreateModel(
            name='SellingInfo',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Sell ID')),
                ('selling_price', models.IntegerField(verbose_name='Selling Price')),
                ('selling_date', models.DateField(db_index=True, verbose_name='Selling Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='car_sales.customerinfo', verbose_name='Customer')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='car_sales.employee', verbose_name='Employee')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='car_sales.store', verbose_name='Store')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='car_sales.vehicleinfo', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name_plural': 'selling info',
                'db_table': 'selling_info',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBudget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Budget ID')),
                ('budget_year', models.IntegerField(verbose_name='Budget Year')),
                ('budget_month', models.IntegerField(verbose_name='Budget Month')),
                ('budget_qty', models.IntegerField(verbose_name='Budget Quantity')),
                ('budget_amount', models.IntegerField(verbose_name='Budget Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='car_sales.employee', verbose_name='Employee')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='car_sales.store', verbose_name='Store')),
            ],
            options={
                'db_table': 'employee_budget',
                'unique_together': {('employee', 'budget_year', 'budget_month', 'store')},
            },
        ),
        migrations.AddIndex(
            model_name='vehicleinfo',
            index=models.Index(fields=['make'], name='vehicle_inf_make_id_c0b227_idx'),
        ),
    ]
