# Generated by Django 6.0.6 on 2026-07-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Password'),
        ),
    ]
