# Generated by Django 6.0.6 on 2026-07-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0002_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='CAr$@lse2014', max_length=25, verbose_name='Password'),
        ),
    ]
