# Generated by Django 6.0.6 on 2026-07-06 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0003_alter_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Inventory ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='available', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='car_sales.employee', verbose_name='Employee')),
                ('selling_info', models.OneToOneField(blank=True, db_column='sell_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item', to='car_sales.sellinginfo', verbose_name='Selling Info')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='car_sales.store', verbose_name='Store')),
                ('vehicle', models.OneToOneField(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='car_sales.vehicleinfo', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name_plural': 'inventories',
                'db_table': 'inventory',
            },
        ),
    ]
