# Generated by Django 6.0.6 on 2026-07-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0004_invoice_add_mmr_discount_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Paid', max_length=20, verbose_name='Payment Status'),
        ),
    ]
