# Generated by Django 6.0.6 on 2026-07-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0004_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('pre-order', 'Pre-order'), ('unavailable', 'Unavailable'), ('available', 'Available')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
