# Generated by Django 6.0.6 on 2026-07-16 11:48

import car_sales.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0006_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHierarchy',
            fields=[
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hierarchy', serialize=False, to='car_sales.employee', verbose_name='Employee')),
                ('created_at', car_sales.models.TruncatedDateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', car_sales.models.TruncatedDateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_hierarchies', to='car_sales.employeerole', verbose_name='Role')),
                ('supervisor', models.ForeignKey(blank=True, db_column='supervisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_hierarchies', to='car_sales.employee', verbose_name='Supervisor')),
                ('supervisor2', models.ForeignKey(blank=True, db_column='supervisor2_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor2_hierarchies', to='car_sales.employee', verbose_name='Supervisor 2')),
                ('supervisor2_role', models.ForeignKey(blank=True, db_column='supervisor2_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor2_role_hierarchies', to='car_sales.employeerole', verbose_name='Supervisor 2 Role')),
                ('supervisor3', models.ForeignKey(blank=True, db_column='supervisor3_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor3_hierarchies', to='car_sales.employee', verbose_name='Supervisor 3')),
                ('supervisor3_role', models.ForeignKey(blank=True, db_column='supervisor3_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor3_role_hierarchies', to='car_sales.employeerole', verbose_name='Supervisor 3 Role')),
                ('supervisor4', models.ForeignKey(blank=True, db_column='supervisor4_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor4_hierarchies', to='car_sales.employee', verbose_name='Supervisor 4')),
                ('supervisor4_role', models.ForeignKey(blank=True, db_column='supervisor4_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor4_role_hierarchies', to='car_sales.employeerole', verbose_name='Supervisor 4 Role')),
                ('supervisor5', models.ForeignKey(blank=True, db_column='supervisor5_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor5_hierarchies', to='car_sales.employee', verbose_name='Supervisor 5')),
                ('supervisor5_role', models.ForeignKey(blank=True, db_column='supervisor5_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor5_role_hierarchies', to='car_sales.employeerole', verbose_name='Supervisor 5 Role')),
                ('supervisor_role', models.ForeignKey(blank=True, db_column='supervisor_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_role_hierarchies', to='car_sales.employeerole', verbose_name='Supervisor Role')),
            ],
            options={
                'verbose_name_plural': 'employee hierarchies',
                'db_table': 'employee_hierarchy',
            },
        ),
    ]
