# Generated by Django 6.0.6 on 2026-07-19 10:23

from django.db import migrations, models


def populate_role_access_levels(apps, schema_editor):
    EmployeeRole = apps.get_model('car_sales', 'EmployeeRole')
    
    # Store-level manager roles
    store_level_managers = [
        "Branch Manager",
        "Sales Manager",
        "Showroom Manager",
        "Fleet Sales Specialist",
        "Senior Sales Executive",
        "Finance & Insurance Officer",
        "Customer Relations Officer",
    ]
    
    for role in EmployeeRole.objects.all():
        role_name = role.role_name
        
        if role_name == "Regional Sales Manager":
            role.access_level = 'country'
            role.is_manager = True
        elif role_name in store_level_managers:
            role.access_level = 'store'
            role.is_manager = True
        elif role_name in ["Sales Executive", "Pre-Owned Vehicle Specialist"]:
            role.access_level = 'own'
            role.is_manager = False
        else:
            # Fallback/unrecognized roles
            role.access_level = 'own'
            role_lower = role_name.lower()
            role.is_manager = "manager" in role_lower or "admin" in role_lower
        
        role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0006_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='access_level',
            field=models.CharField(choices=[('country', 'Country-level'), ('store', 'Store-level'), ('own', 'Own-data-only')], default='own', max_length=50, verbose_name='Access Level'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Is Manager'),
        ),
        migrations.RunPython(populate_role_access_levels, reverse_code=migrations.RunPython.noop),
    ]
