# Generated by Django 6.0.6 on 2026-07-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0008_employeerole_access_level_employeerole_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerole',
            name='is_manager',
        ),
    ]
