# Generated by Django 6.0.6 on 2026-07-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0009_employeerole_level_employeerole_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerole',
            name='access_level',
        ),
    ]
