# Generated by Django 6.0.6 on 2026-08-03 18:25

import car_sales.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0013_populate_customer_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Message ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', car_sales.models.TruncatedDateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', car_sales.models.TruncatedDateTimeField(auto_now=True, verbose_name='Update Time')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_messages', to='car_sales.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_messages', to='car_sales.employee', verbose_name='Employee')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_messages', to='car_sales.store', verbose_name='Store')),
            ],
            options={
                'verbose_name_plural': 'customer messages',
                'db_table': 'customer_message',
            },
        ),
    ]
