# Generated by Django 6.0.6 on 2026-07-30 06:00

import car_sales.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_sales', '0013_populate_customer_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', car_sales.models.TruncatedDateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', car_sales.models.TruncatedDateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='car_sales.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name_plural': 'carts',
                'db_table': 'ecommerce_cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('order_number', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='Order Number')),
                ('total_amount', models.IntegerField(verbose_name='Total Amount')),
                ('deposit_amount', models.IntegerField(default=0, verbose_name='Deposit Amount')),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('DEPOSIT_PAID', 'Deposit Paid'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Order Status')),
                ('fulfillment_type', models.CharField(choices=[('STORE_PICKUP', 'Store Pickup'), ('HOME_DELIVERY', 'Home Delivery')], default='STORE_PICKUP', max_length=20, verbose_name='Fulfillment Type')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Address')),
                ('created_at', car_sales.models.TruncatedDateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', car_sales.models.TruncatedDateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='car_sales.customer', verbose_name='Customer')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='car_sales.inventory', verbose_name='Inventory Item')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_order', to='car_sales.invoice', verbose_name='Invoice')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecommerce_orders', to='car_sales.store', verbose_name='Store')),
            ],
            options={
                'verbose_name_plural': 'orders',
                'db_table': 'ecommerce_order',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('gateway_transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Gateway Transaction ID')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('amount', models.IntegerField(verbose_name='Amount Paid')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', car_sales.models.TruncatedDateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', car_sales.models.TruncatedDateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ecommerce.order', verbose_name='Order')),
            ],
            options={
                'verbose_name_plural': 'payment transactions',
                'db_table': 'ecommerce_payment_transaction',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', car_sales.models.TruncatedDateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.cart', verbose_name='Cart')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='car_sales.inventory', verbose_name='Inventory Item')),
            ],
            options={
                'verbose_name_plural': 'cart items',
                'db_table': 'ecommerce_cart_item',
                'unique_together': {('cart', 'inventory')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', car_sales.models.TruncatedDateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='car_sales.customer', verbose_name='Customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='car_sales.vehicleinfo', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name_plural': 'wishlists',
                'db_table': 'ecommerce_wishlist',
                'unique_together': {('customer', 'vehicle')},
            },
        ),
    ]
