# Generated by Django 6.0.6 on 2026-07-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='payment',
        ),
    ]
